import random

def generate_random_joke():
    jokes = [
        "Why did the computer go to therapy? It had too many bytes of emotional baggage!",
        "I told my computer I needed a break... now it won't stop sending me vacation ads!",
        "Why was the JavaScript developer sad? Because he didn't know how to 'null' his feelings!",
        "Why did the developer go broke? Because he used up all his cache!",
        "Why was the database administrator lonely? Because his relationships were never 'normalized'!",
        "What do you call a fake noodle? An impasta!",
        "Why don't scientists trust atoms? Because they make up everything!",
        "I'm reading a book on anti-gravity... it's impossible to put down!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "What do you call cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "I used to play piano by ear, but now I use my hands!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "I told my wife she was drawing her eyebrows too high... she looked surprised!",
        "I'm reading a book on the history of glue... can't put it down!",
        "Why don't some couples go to the gym? Because some relationships don't work out!",
        "Why did the chicken join a band? Because it had the drumsticks!",
        "Why couldn't the bicycle stand up by itself? It was two-tired!",
        "What did one plate say to the other plate? Lunch is on me!",
        "Why was the math book sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "Why don't scientists trust atoms? Because they make up everything!",
        "What do you call fake spaghetti? An impasta!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "Why did the bicycle fall over? Because it was two-tired!",
        "Why don't some couples go to the gym? Because some relationships don't work out!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "What do you call fake spaghetti? An impasta!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "Why did the bicycle fall over? Because it was two-tired!",
        "Why don't some couples go to the gym? Because some relationships don't work out!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "Why don't some couples go to the gym? Because some relationships don't work out!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "What did one ocean say to the other ocean? Nothing, they just waved!",
        "Why did the math book look sad? Because it had too many problems!",
        "Why was the belt arrested? For holding up a pair of pants!",
        "What do you call a can opener that doesn't work? A can't opener!",
        "What's orange and sounds like a parrot? A carrot!",
        "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
        "What's green and sings? Elvis Parsley!",
        "Why don't oysters donate to charity? Because they're shellfish!",
        "What do you call fake spaghetti? An impasta!",
        "What do you call a sleeping bull? A bulldozer!",
        "Why did the tomato turn red? Because it saw the salad dressing!",
        "What did the janitor say when he jumped out of the closet? Supplies!",
        "What do you call a belt made of watches? A waist of time!",
        "Why was the math book sad? Because it had too many problems!",
        "Why couldn't the bicycle stand up by itself? Because it was two-tired!",
        "What do you get when you cross a snowman and a vampire? Frostbite!",
        "Why don't eggs tell jokes? Because they might crack up!",
        "What do you call a cheese that isn't yours? Nacho cheese!",
        "Why don't skeletons fight each other? They don't have the guts!",
    ]
    return random.choice(jokes)

if __name__ == "__main__":
    while True:
        input("Press enter to hear a joke...")
        print(generate_random_joke())
